# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'



steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.x'
- script: npm install
  workingDirectory: pantklient
- script: npm run build
  workingDirectory: pantklient
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'pantklient/build' 
    includeRootFolder: false
    archiveFile: 'pantklient/dist/pantklient-build.zip'
    archiveType: zip
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'pantklient/dist'
    publishLocation: Container
    artifactName: 'pantklient'
    targetPath: 'pantklient/dist'
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'
    packageType: sdk
- script: dotnet restore
  workingDirectory: PantAPI
- script: dotnet build
  workingDirectory: PantAPI
- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
  workingDirectory: PantAPI
- task: PublishBuildArtifacts@1